variables:
  PROJECT_NAME: "commission-engine-payment-lambda"
  SONAR_EXCLUSIONS: "test/**, src/util/secrets.go, src/util/config.go, src/request/request.go, src/main.go"
  GO_BUILD_OUTPUT : "main"
  GO_BUILD_INPUT: "cmd/main.go"
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

include:
  - project: 'community/easy-ci'
    ref: "master"
    file: '.gitlab-ci/workflow.yml'

go-test:
  stage: test
  script:
    - echo "No need to scan"
#    - make test

  artifacts:
      paths:
        - coverage.out

  rules:
    - !reference [.never-duplicate-pipeline, rules]
    - when: on_success


# Perform composition analysis on docker image that packages the app
#image-scan:
#  stage: image-scan
#  script:
#    - echo "No need to scan"
#  rules:
#    - !reference [.docker-image-scan, rules]


# This Job scans branches only
#code-gate:
#  stage: sonar-scan
#  script:
#    - echo "No cov for now"
##    - sonar-scanner -Dsonar.projectName=$SONAR_PROJECT_NAME
##      -Dsonar.projectKey=GL-$CI_PROJECT_ID
##      -Dsonar.qualitygate.wait=true
##      -Dsonar.branch.name=$CI_COMMIT_BRANCH
##      -Dsonar.exclusions="$SONAR_EXCLUSIONS"
##      -Dsonar.go.coverage.reportPaths=coverage.out
#  rules:
#    - !reference [.sonarqube-scan-branch, rules]

# This job scans merge requests only
code-gate-mr:
  stage: sonar-scan
  script:
    - echo "No cov for now"
#    - sonar-scanner -Dsonar.projectName=$SONAR_PROJECT_NAME
#      -Dsonar.projectKey=GL-$CI_PROJECT_ID
#      -Dsonar.qualitygate.wait=true
#      -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
#      -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
#      -Dsonar.pullrequest.key="GL-$CI_PROJECT_ID"
#      -Dsonar.exclusions="$SONAR_EXCLUSIONS"
#      -Dsonar.go.coverage.reportPaths=coverage.out
  rules:
    - !reference [.sonarqube-scan-merge-request, rules]


#go-build:
#  stage: package
#  script:
#    - $GO_BUILD_VARIABLES go build cmd/main.go
#  artifacts:
#    paths:
#      - main
#    expire_in: 1 day
#  rules:
#    - !reference [.app-package-to-be-used-by-docker, rules]
#


